/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cdio_math_misc_JNIHyperGeometricFunction */

#ifndef _Included_cdio_math_misc_JNIHyperGeometricFunction
#define _Included_cdio_math_misc_JNIHyperGeometricFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cdio_math_misc_JNIHyperGeometricFunction
 * Method:    HGF
 * Signature: (IIIDI[DI[DI[DI[D)D
 */
JNIEXPORT jdouble JNICALL Java_cdio_math_misc_JNIHyperGeometricFunction_HGF
  (JNIEnv *, jclass, jint, jint, jint, jdouble, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
